### ISSUE TITLE
I can not run it 

### ISSUE THREAD

**Issue by polaris-han** [tikkid/JetbrainKiller#1]
when I run it , it went wrong:
<img width="822" alt="截屏2023-09-20 09 43 16" src="https://github.com/tikkid/JetbrainKiller/assets/35481705/3b625f7f-4d99-4650-8cfb-0cf4a0ca09fa">
my system:
<img width="392" alt="截屏2023-09-20 09 44 01" src="https://github.com/tikkid/JetbrainKiller/assets/35481705/db3cbc43-f997-4d99-8774-a08ec7a78eb8">
please tell me what I can do

**Comment by 1595901624** [comment]
Please run `chmod +x ./jetbrain_killer` first.

**Comment by polaris-han** [comment]
> Please run `chmod +x ./jetbrain_killer` first.

It works, thank you
